config/routes.rb
Rails.application.routes.draw do
  # admin page
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # users
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # root
  root "home#index"

  # items
  resources :items do
    collection do
      get 'search'
    end
  end

  # categories
  get '/category', to: 'categories#index', as: :categories
  get '/category/list/:id', to: 'categories#get_list', as: :category_list

  # profile page
  get '/users/profile/:id', to: 'users#get_profile', as: :user_profile

  # new review form
  get '/review/form/:id', to: 'reviews#show_form', as: :show_review_form

  # add new review
  post '/review/add/:id', to: 'reviews#add_review', as: :add_review

  # favorite item
  post '/favorite/item/:id', to: 'favorites#add_item', as: :favorite_item
  # remove item form favorite
  post '/favorite/item/:id/remove', to: 'favorites#remove_item', as: :favorite_item_remove

  # follow user
  post '/follow/user/:follower_id', to: 'follows#follow_user', as: :follow
  # unfollow user
  post '/follow/user/:follower_id/remove', to: 'follows#unfollow_user', as: :unfollow
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # validation
  validates :name,
            presence: true,
            length: { maximum: 20 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # carrierwave
  mount_uploader :image, ImageUploader

  # relation
  belongs_to :age
  belongs_to :gender
  belongs_to :residence
  has_many :reviews
  has_many :favorites
  has_many :items, through: :favorites
  has_many :follows
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    @user.age_id = params[:age][:id]
    @user.gender_id = params[:gender][:id]
    @user.residence_id = params[:residence][:id]
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    else
      @user.save
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def get_profile
    @user = User.find(params[:id])

    render :profile
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<!-- page title -->
<%= render partial: 'shared/page_title', locals: { page_title: @user.name +
'さんのプロフィールデータ' } %>

<!-- header -->
<%= render partial: 'shared/header' %>

<!-- flash message -->
<%= render partial: 'shared/flash_message' %>

<!--main -->
<main class="main">
  <div class="wrap">
    <div class="profile flex">
      <div class="profile--before flex">
        <div class="profile__upper flex">
          <figure class="profile__image--user">
            <% if @user.image? %> <%= image_tag @user.image.url %> <% end %>
          </figure>
          <div class="profile__numbers flex">
            <div class="flex">
              <div>
                <span class="profile__number"><%= @user.reviews.size %></span>
                <span class="profile__ruby">レビュー</span>
              </div>
              <div>
                <span class="profile__number"><%= get_number_of_follow(@user) %></span>
                <span class="profile__ruby">フォロー</span>
              </div>
              <div>
                <span class="profile__number"><%= get_number_of_follower(@user) %></span>
                <span class="profile__ruby">フォロワー</span>
              </div>
            </div>
            <% unless @user == current_user %>
            <% if is_followed(@user.id) %>
            <%= button_to 'フォロー解除', unfollow_path(@user), class: 'profile__button red' %>
            <% else %>
            <%= button_to 'フォローする', follow_path(@user), class: 'profile__button' %>
            <% end %>
            <% end %>
          </div>
        </div>
        <div>
          <h3 class="profile__name"><%= @user.name %></h3>
          <p>
            <%= @user.age.title %>/<%= @user.gender.title %>/<%=
            @user.residence.name %>
          </p>
        </div>
      </div>
      <div class="profile--after">
        <h3 class="profile__heading active">レビュー</h3>
        <h3 class="profile__heading">お気に入り商品</h3>
        <div class="profile-review__wrap">
          <% if is_exists_user_review(@user.id) %> <% @user.reviews.each do
        |review| %>
          <div class="profile-review">
            <div class="profile-review__upper flex">
              <div class="profile-review__image--item">
                <%= image_tag review.item.image.url %>
              </div>
              <div class="profile-review__data">
                <h4 class="profile-review__name">
                  <%= link_to review.item.name, item_path(review.item.id)
                %>
                </h4>
                <span class="profile-review__label">
                  <%= link_to review.item.category.name, category_list_path(review.item.category.id) %>
                </span>
                <p class="profile-review__number">
                  <%= get_number_of_review(review.item.id) %>件のレビュー
                </p>
              </div>
            </div>
            <div class="item-review__lower">
              <p class="item-review__text"><%= review.body %></p>
              <p class="item-review__date">
                <%= show_datetime(review.created_at) %>
              </p>
            </div>
          </div>
          <% end %> <% else %>
          <figure class="profile__image">
            <%= image_tag 'img_item01.png' %>
          </figure>
          <% end %>
        </div>
        <% if is_exists_user_favorite(@user.id) %>
        <div class="profile-favorite__wrap flex hidden">
          <% @user.favorites.each do |favorite| %>
          <%= link_to item_path(favorite.item.id), class: 'profile-favorite__link' do %>
          <figure class="profile-favorite__image">
            <%= image_tag favorite.item.image.url %>
            <figcaption>
              <%= favorite.item.name %>
            </figcaption>
          </figure>
          <% end %>
          <% end %>
          <% else %>
          <figure class="profile__image">
            <%= image_tag 'img_item01.png' %>
          </figure>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

<!-- footer -->
<%= render partial: 'shared/footer' %>