config/routes.rb
Rails.application.routes.draw do
  # admin page
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # users
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # root
  root "home#index"

  # items
  resources :items do
    collection do
      get 'search'
    end
  end

  # categories
  get '/category', to: 'categories#index', as: :categories
  get '/category/list/:id', to: 'categories#get_list', as: :category_list

  # profile page
  get '/users/profile/:id', to: 'users#get_profile', as: :user_profile

  # new review form
  get '/review/form/:id', to: 'reviews#show_form', as: :show_review_form

  # add new review
  post '/review/add/:id', to: 'reviews#add_review', as: :add_review

  # favorite item
  post '/favorite/item/:id', to: 'favorites#add_item', as: :favorite_item
  # remove item form favorite
  post '/favorite/item/:id/remove', to: 'favorites#remove_item', as: :favorite_item_remove

  # follow user
  post '/follow/user/:follower_id', to: 'follows#follow_user', as: :follow
  # unfollow user
  post '/follow/user/:follower_id/remove', to: 'follows#unfollow_user', as: :unfollow
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
     return unless user && user&.admin? # 管理者じゃなかったらこのメソッドを抜ける

    can :access, :rails_admin # 管理者画面のアクセス許可
    can :manage, :all # 管理権限許可
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/age.rb
class Age < ApplicationRecord
  # relation
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # relation
  has_many :items
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # relation
  belongs_to :user
  belongs_to :item

  # validation
  validates :user_id, uniqueness: { scope: :item_id }
end

app/models/follow.rb
class Follow < ApplicationRecord
  # relation
  belongs_to :user

  # validation
  validates :user_id, uniqueness: { scope: :follower_id }
end

app/models/gender.rb
class Gender < ApplicationRecord
  # relation
  has_many :users
end

app/models/item.rb
class Item < ApplicationRecord
  # relation
  belongs_to :category
  has_many :reviews
  has_many :favorites
  has_many :users, through: :favorites

  # carrierwave
  mount_uploader :image, ImageUploader
end

app/models/residence.rb
class Residence < ApplicationRecord
  # relation
  has_many :users
end

app/models/review.rb
class Review < ApplicationRecord
  # relation
  belongs_to :user
  belongs_to :item

  # validation
  validates :body,
            presence: true,
            length: { maximum: 300 }
  validates :star,
            presence: true
  validates :user_id, uniqueness: { scope: :item_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # validation
  validates :name,
            presence: true,
            length: { maximum: 20 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # carrierwave
  mount_uploader :image, ImageUploader

  # relation
  belongs_to :age
  belongs_to :gender
  belongs_to :residence
  has_many :reviews
  has_many :favorites
  has_many :items, through: :favorites
  has_many :follows
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def follow_user
    user = current_user
    follow = user.follows.new(follows_params)

    if follow.save
      redirect_to request.referer, notice: 'フォローしました'
    else
      render "users/profile"
    end
  end

  def unfollow_user
    user = current_user
    follower = user.follows.find_by(follower_id: params[:follower_id])
    follower.destroy

    redirect_to request.referer, notice: 'フォローを解除しました'
  end

  # private
  private
  def follows_params
    params.permit(:follower_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_q_header, only: %i(show search)

  def index
    @items = Item.all.order(id: :desc).page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def search
    @result = @q_header.result.page(params[:page])
    @search_word = params[:q]['name_or_description_gt']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def get_profile
    @user = User.find(params[:id])

    render :profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # BASE_TITLE = "Store".freeze
  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{page_title}"
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def get_all_collection(model)
    model.all
  end

  def get_featured_category
    category_ids = Item.group(:category_id).count
    sorted_res = category_ids.sort_by { |_, v| v }.reverse.to_h
    res = sorted_res.keys
    arr = []
    9.times do |i|
      ct = Category.find(res[i])
      arr.push(ct)
    end
    arr
  end

  def is_exists_current_user_review(item_id)
    item = Item.find(item_id)
    item.reviews.any? && item.reviews[0].user_id == current_user.id
  end

  def is_exists_review(item_id)
    item = Item.find(item_id)
    item.reviews.any?
  end

  def show_datetime(d)
    d.strftime("%Y-%m-%d %H:%M:%S")
  end

  def show_stars(score)
    tag(:img, src: '/assets/ico_star-on.png', class: ('item-review__image--star')) * score +
    tag(:img, src: '/assets/ico_star-off.png', class: ('item-review__image--star')) * (5 - score)
  end

  def is_exists_user_review(user_id)
    user = User.find(user_id)
    user.reviews.any?
  end

  def is_exists_user_favorite(user_id)
    user = User.find(user_id)
    user.favorites.any?
  end

  def get_number_of_review(item_id)
    item = Item.find(item_id)
    item.reviews.size
  end

  def get_all_review
    Review.count
  end

  def get_larger_review
    res = Review.group(:item_id).order('count_item_id DESC').count(:item_id).keys

    arr = []

    res.first(5).each do |v|
      arr.push(v)
    end

    Item.where(id: arr).reverse
  end

  def put_class(value)
    case value
    when 0 then
      'first'
    when 1 then
      'second'
    when 2 then
      'third'
    end
  end

  def get_score_ranking
    Review.select('item_id, SUM(star) AS total_star')
    .group(:item_id)
    .order('total_star desc')
    .limit(5)
  end

  def is_exists_favorite(item_id)
    user = current_user
    user.favorites.where(item_id: item_id).any?
  end

  def is_followed(user_id)
    user = current_user
    user.follows.where(follower_id: user_id).any?
  end

  def get_number_of_follow(user_id)
    Follow.where(user_id: user_id).size
  end

  def get_number_of_follower(user_id)
    Follow.where(follower_id: user_id).size
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- jquery -->
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  <!-- slick -->
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css" />

  <!-- fontawesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/shared/_drawer_menu.html.erb
<!-- drawer menu -->
<div class="drawer__overlay"></div>
<div class="drawer">
  <div class="drawer__inner">
    <ul class="drawer__list">
      <li class="drawer__menu first">
        <%= link_to image_tag('bnr_drawer.jpg') %>
      </li>
      <li class="drawer__menu"><%= link_to 'トップ', root_path %></li>
      <% if user_signed_in? %>
      <li class="drawer__menu">
        <%= link_to current_user.name + 'さん', user_profile_path(current_user)
        %>
      </li>
      <% else %>
      <li class="drawer__menu">
        <%= link_to 'ログイン・新規登録', new_user_session_path %>
      </li>
      <% end %>
      <li class="drawer__menu"><%= link_to '新商品', items_path %></li>
      <li class="drawer__menu"><%= link_to '新着レビュー', '#' %></li>
      <% if user_signed_in? %>
      <li class="drawer__menu"><%= link_to 'お気に入り', '#' %></li>
      <li class="drawer__menu"><%= link_to 'フォロー会員', '#' %></li>
      <% end %>
      <li class="drawer__menu small"><%= link_to 'パイビューとは', '#' %></li>
      <li class="drawer__menu"><%= link_to 'カテゴリー一覧', '#' %></li>
      <li class="drawer__menu"><%= link_to 'グッドレビュー', '#' %></li>
      <li class="drawer__menu"><%= link_to 'ピックアップ', '#' %></li>
      <li class="drawer__menu"><%= link_to 'キャンペーン', '#' %></li>
      <li class="drawer__menu"><%= link_to 'コラム', '#' %></li>
      <li class="drawer__menu"><%= link_to '運営会社', '#' %></li>
      <li class="drawer__menu">
        <%= link_to '個人情報の取り扱いについて', '#' %>
      </li>
      <li class="drawer__menu"><%= link_to '利用規約', '#' %></li>
      <li class="drawer__menu"><%= link_to 'サイトマップ', '#' %></li>
      <li class="drawer__menu"><%= link_to 'よくある質問', '#' %></li>
      <li class="drawer__menu"><%= link_to '問い合わせ', '#' %></li>
    </ul>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
<div id="error_explanation">
  <ul class="error-message">
    <% resource.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_flash_message.html.erb
<% if flash[:notice] %>
<p class="notice"><%= notice %></p>
<% end %>
<% if flash[:alert] %>
<p class="alert"><%= alert %></p>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer__inner flex">
    <ul class="footer__nav flex">
      <li class="footer__menu"><%= link_to 'トップ', root_path %></li>
      <li class="footer__menu"><%= link_to 'パイビューとは', '#' %></li>
      <li class="footer__menu"><%= link_to 'カテゴリー一覧', '#' %></li>
      <li class="footer__menu"><%= link_to '運営会社', '#' %></li>
      <li class="footer__menu">
        <%= link_to '個人情報の取扱いについて', '#' %>
      </li>
      <li class="footer__menu"><%= link_to '利用規約', '#' %></li>
      <li class="footer__menu"><%= link_to 'サイトマップ', '#' %></li>
    </ul>
    <h4 class="footer__heading">シェアビュー公式アカウント</h4>
    <ul class="footer__icons flex">
      <li class="footer__item"><%= link_to image_tag('ico_line.png') %></li>
      <li class="footer__item"><%= link_to image_tag('ico_twitter.png') %></li>
      <li class="footer__item"><%= link_to image_tag('ico_insta.png') %></li>
    </ul>
    <fugure class="footer__logo">
      <%= link_to image_tag('logo_footer.png'), root_path %>
    </fugure>
    <small class="footer__text--copy"
      >Copyright (C) SHINOPAI Co.,Ltd. All Rights Reserved.</small
    >
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="wrap">
    <nav class="header__nav flex">
      <div class="header__menu--before flex">
        <%= link_to image_tag('ico_menu.gif', class: 'header__icon'), '#' %>
        <h1>
          <%= link_to image_tag('logo_site.png', class: 'header__logo'),
          root_path %>
        </h1>
      </div>
      <ul class="header__menu--after flex">
        <li class="header__item--first"><%= link_to 'カテゴリからさがす', categories_path %></li>
        <li class="header__item--second">キーワードでさがす</li>
        <% if user_signed_in? %>
        <li>
          <%= link_to current_user.name + 'さん',
          user_profile_path(current_user), class: 'header__link--profile' %>
        </li>
        <% else %>
        <li>
          <%= link_to 'ログイン・新規登録', new_user_session_path, class:
          'header__link' %>
        </li>
        <% end %>
      </ul>
      <ul class="header__menu--after sp">
        <li class="header__item--first sp"><%= link_to categories_path do  %>
          <%= image_tag 'ico_cat_sp.gif' %>
          <% end %>
        </li>
        <li class="header__item--second sp">
          <%= image_tag 'ico_search_sp.gif' %>
        </li>
      </ul>
    </nav>
  </div>
</header>

<!-- search form -->
<div class="search-form">
  <div class="wrap">
    <div class="search-form__inner flex">
      <%= search_form_for @q_header, url: search_items_path, class:
      'search-form__form' do |search| %> <%= search.search_field :name_or_description_gt, class: 'search-form__textfield' %>
      <%= search.search_field :name_or_description_gt, class: 'search-form__textfield sp', placeholder: 'キーワードでさがす' %>
      <%= search.submit '検索', class: 'search-form__submit' %>
      <%= button_tag sanitize('<i class="fas fa-search"></i>'), :type => "submit",
    :class =>"search-form__submit sp fas" %>
      <% end %>
      <p class="search-form__text">キャンセル</p>
    </div>
  </div>
</div>

app/views/shared/_page_title.html.erb
<% provide(:title, page_title) %>