config/routes.rb
Rails.application.routes.draw do
  # admin page
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # users
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # root
  root "home#index"

  # items
  resources :items do
    collection do
      get 'search'
    end
  end

  # categories
  get '/category', to: 'categories#index', as: :categories
  get '/category/list/:id', to: 'categories#get_list', as: :category_list

  # profile page
  get '/users/profile/:id', to: 'users#get_profile', as: :user_profile

  # new review form
  get '/review/form/:id', to: 'reviews#show_form', as: :show_review_form

  # add new review
  post '/review/add/:id', to: 'reviews#add_review', as: :add_review

  # favorite item
  post '/favorite/item/:id', to: 'favorites#add_item', as: :favorite_item
  # remove item form favorite
  post '/favorite/item/:id/remove', to: 'favorites#remove_item', as: :favorite_item_remove

  # follow user
  post '/follow/user/:follower_id', to: 'follows#follow_user', as: :follow
  # unfollow user
  post '/follow/user/:follower_id/remove', to: 'follows#unfollow_user', as: :unfollow
end

app/models/item.rb
class Item < ApplicationRecord
  # relation
  belongs_to :category
  has_many :reviews
  has_many :favorites
  has_many :users, through: :favorites

  # carrierwave
  mount_uploader :image, ImageUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_q_header, only: %i(show search)

  def index
    @items = Item.all.order(id: :desc).page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def search
    @result = @q_header.result.page(params[:page])
    @search_word = params[:q]['name_or_description_gt']
  end
end

app/views/items/index.html.erb
<!-- page title -->
<%= render partial: 'shared/page_title', locals: { page_title:
'新商品' } %>

<!-- header -->
<%= render partial: 'shared/header' %>

<!--main -->
<main class="main">
  <div class="wrap">
    <div class="items flex">
      <% @items.each do |item| %>
      <div class="items__item">
        <%= link_to item_path(item) do %>
        <div class="items__image">
          <%= image_tag item.image.url %>
        </div>
        <h4 class="items__title"><%= item.name %></h4>
        <% end %>
        <span class="items__date"><%= item.release_date %></span>
        <i class="fas fa-heart items__icon"></i>
      </div>
      <% end %>
    </div>
    <%= paginate @items %>
  </div>
</main>

<!-- footer -->
<%= render partial: 'shared/footer' %>

app/views/items/search.html.erb
<!-- page title -->
<%= render partial: 'shared/page_title', locals: { page_title: '「' + @search_word + '」の検索結果'} %>

<!-- header -->
<%= render partial: 'shared/header' %>

<!--main -->
<main class="main">
  <div class="wrap">
    <div class="items flex">
      <% @result.each do |item| %>
      <div class="items__item">
        <%= link_to item_path(item) do %>
        <div class="items__image">
          <%= image_tag item.image.url %>
        </div>
        <h4 class="items__title"><%= item.name %></h4>
        <% end %>
        <span class="items__date"><%= item.release_date %></span>
        <div id="favorite-app"></div>
      </div>
      <% end %>
    </div>
    <%= paginate @result %>
  </div>
</main>

<!-- footer -->
<%= render partial: 'shared/footer' %>

app/views/items/show.html.erb
<!-- page title -->
<%= render partial: 'shared/page_title', locals: { page_title: @item.name +
'の商品ページ' } %>

<!-- header -->
<%= render partial: 'shared/header' %>

<!-- flash -->
<%= render partial: 'shared/flash_message' %>

<!--main -->
<main class="main">
  <div class="wrap">
    <div class="item-dtl flex">
      <div class="item-dtl--before flex">
        <div>
          <div class="item-dtl__image--item">
            <% if @item.image? %> <%= image_tag @item.image.url %> <% end %>
          </div>
          <% if is_exists_favorite(@item) %>
          <%= button_to favorite_item_remove_path(@item), class: 'item-dtl__submit' do %>
          <i class="fas fa-heart item-dtl__icon red" title="お気に入り登録済"></i>
          <% end %>
          <% else %>
          <%= button_to favorite_item_path(@item), class: 'item-dtl__submit' do %>
          <i class="fas fa-heart item-dtl__icon"></i>
          <% end %>
          <% end %>
        </div>
        <div>
          <%= link_to category_list_path(@item.category.id) do %>
          <span class="item-dtl__label"><%= @item.category.name %></span>
          <% end %>
          <span class="item-dtl__date">登録日:&nbsp;<%= @item.created_at.strftime('%Y.%m.%d') %></span>
        </div>
        <h3 class="item-dtl__title"><%= @item.name %></h3>
        <% if user_signed_in? && !is_exists_current_user_review(@item.id) %> <%= link_to 'レビューする', show_review_form_path(@item), class: 'item-dtl__link' %>
        <% end %>
      </div>
      <div class="item-dtl--after">
        <h3 class="item-dtl__heading"><%= @item.reviews.size %>件のレビュー</h3>
        <% if is_exists_review(@item.id) %>
        <% @item.reviews.each do |review| %>
        <div class="item-review">
          <div class="item-review__upper flex">
            <div class="item-review__image--user">
              <%= image_tag review.user.image.url %>
            </div>
            <div class="item-review__data">
              <p class="item-review__name"><%= link_to review.user.name, user_profile_path(review.user.id) %>さん</p>
              <p class="item-review__dtl"><%= review.user.age.title %>/<%= review.user.gender.title %>/<%= review.user.residence.name %></p>
              <p class="item-review__score"><%= show_stars(review.star) %><span><%= review.star.to_f %></span></p>
            </div>
          </div>
          <div class="item-review__lower">
            <p class="item-review__text"><%= review.body %></p>
            <p class="item-review__date"><%= show_datetime(review.created_at) %></p>
          </div>
        </div>
        <% end %>
        <% else %>
        <figure class="item-dtl__image">
          <%= image_tag 'img_item01.png' %>
        </figure>
        <% end %>
      </div>
    </div>
  </div>
</main>

<!-- footer -->
<%= render partial: 'shared/footer' %>