config/routes.rb
Rails.application.routes.draw do
  # admin page
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # users
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # root
  root "home#index"

  # items
  resources :items do
    collection do
      get 'search'
    end
  end

  # categories
  get '/category', to: 'categories#index', as: :categories
  get '/category/list/:id', to: 'categories#get_list', as: :category_list

  # profile page
  get '/users/profile/:id', to: 'users#get_profile', as: :user_profile

  # new review form
  get '/review/form/:id', to: 'reviews#show_form', as: :show_review_form

  # add new review
  post '/review/add/:id', to: 'reviews#add_review', as: :add_review

  # favorite item
  post '/favorite/item/:id', to: 'favorites#add_item', as: :favorite_item
  # remove item form favorite
  post '/favorite/item/:id/remove', to: 'favorites#remove_item', as: :favorite_item_remove

  # follow user
  post '/follow/user/:follower_id', to: 'follows#follow_user', as: :follow
  # unfollow user
  post '/follow/user/:follower_id/remove', to: 'follows#unfollow_user', as: :unfollow
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_current_user
  before_action :find_item

  def show_form
    @review = @user.reviews.build

    render :new
  end

  def add_review
    @review = @user.reviews.new(reviews_params)
    @review.item_id = params[:id]

    if @review.save
      redirect_to user_profile_path(@user), notice: 'レビューを投稿しました'
    else
      render :new
    end
  end



  # private
  private
    def reviews_params
      params.require(:review).permit(:body, :star)
    end

    def find_current_user
      @user = User.find(current_user.id)
    end

    def find_item
      @item = Item.find(params[:id])
    end
end

app/views/reviews/new.html.erb
<!-- page title -->
<%= render partial: 'shared/page_title', locals: { page_title:
'新規レビュー投稿' } %>

<!-- header -->
<%= render partial: 'shared/header' %>

<!--main -->
<main class="main">
  <div class="wrap">
    <div class="review flex">
      <figure class="review__image">
        <% if @item.image? %> <%= image_tag @item.image.url %> <% end %>
      </figure>
      <div class="review__item--after">
        <h2 class="review__heading"><%= @item.name %>の新規レビュー</h2>
        <%= form_with model: @review, url: add_review_path(@item), class:
        'review__form' do |review| %> <%= render "shared/error_messages",
        resource: @review %>
        <div class="review__form-item">
          <%= review.label :star, '評価', class: 'review__label' %> <%=
          review.number_field :star, min: 0, max: 5, class: 'review__number' %>
        </div>
        <div class="review__form-item">
          <%= review.label :body, '内容', class: 'review__label' %> <%=
          review.text_area :body, rows: 10, class: 'review__textarea' %>
        </div>
        <div class="review__form-item">
          <%= review.submit 'レビューする', class: 'review__submit' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

<!-- footer -->
<%= render partial: 'shared/footer' %>